version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.6.5"
    ACTION: "plan"
phases:
  install:
    runtime-versions: 
      python: 3.11
    on-failure: ABORT       
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - aws --version
  pre_build:
    on-failure: ABORT     
    commands:
      - echo terraform execution started on `date`            
  build:
    on-failure: ABORT   
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - ls -lrt "$CODEBUILD_SRC_DIR"
      - DATADOG_API_KEY=$(aws secretsmanager get-secret-value --secret-id datadog_keys)
      - DATADOG_APP_KEY=$(aws secretsmanager get-secret-value --secret-id datadog_app_key)
      - export TF_VAR_datadog_api_key=$DATADOG_API_KEY
      - export TF_VAR_datadog_app_key=$DATADOG_APP_KEY
      - terraform --version
      - terraform init -input=false
      - |
        if [ "$ACTION" = "validate" ]; then 
          terraform validate
        fi
      - |
        if [ "$ACTION" = "plan" ]; then
          terraform plan -lock=false -input=false
        fi
      - |
        if [ "$ACTION" = "apply" ]; then
          terraform apply -input=false -auto-approve
        fi
      - |
        if [ "$ACTION" = "destroy" ]; then
          terraform destroy -input=false -auto-approve
        fi
  post_build:
    on-failure: CONTINUE   
    commands:
      - echo terraform execution completed on `date`   